# Generated by Django 4.0 on 2022-05-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCheckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField(verbose_name='检测文字')),
                ('check_result', models.CharField(blank=True, max_length=100, verbose_name='识别结果')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
            ],
            options={
                'verbose_name': '文字检测',
                'verbose_name_plural': '文字检测',
                'db_table': 'class_check',
            },
        ),
    ]
