# Generated by Django 4.0.5 on 2023-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_handle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'db_user_info',
            },
        ),
    ]
